language: python
dist: xenial
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: pypy2.7-6.0.0
    - python: pypy3.5-6.0.0
    - python: 2.7
      env: PURE_PYTHON=1
install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
  - pip install -U -e .[test,docs]
script:
  - coverage run setup.py test -q
  - coverage run -a -m sphinx -b doctest -d docs/_build/doctrees docs docs/_build/doctest
after_success:
  - coveralls
notifications:
  email: false
cache: pip
